try:
    print(x)
except:
    print("An Exception has occurred")
